'use client';

import React, { useState, useRef, useEffect } from 'react';
import { QrCode, Loader2, Download } from 'lucide-react';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { Button } from '@/components/ui/button';

export function QrToPdfTool() {
  const [content, setContent] = useState('');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [qrSize, setQrSize] = useState<'small' | 'medium' | 'large'>('medium');
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const sizeMap = { small: 200, medium: 280, large: 360 };

  useEffect(() => {
    if (!content) return;
    const generate = async () => {
      try {
        const QRCode = (await import('qrcode')).default;
        if (canvasRef.current) {
          await QRCode.toCanvas(canvasRef.current, content, { width: sizeMap[qrSize], margin: 2 });
        }
      } catch { /* ignore preview errors */ }
    };
    const t = setTimeout(generate, 300);
    return () => clearTimeout(t);
  }, [content, qrSize]);

  const process = async () => {
    if (!content) return;
    setIsProcessing(true); setError(null);
    try {
      const QRCode = (await import('qrcode')).default;
      const qrCanvas = document.createElement('canvas');
      const qrPx = sizeMap[qrSize];
      await QRCode.toCanvas(qrCanvas, content, { width: qrPx, margin: 2 });
      const qrDataUrl = qrCanvas.toDataURL('image/png');
      const qrBytes = await (await fetch(qrDataUrl)).arrayBuffer();

      const doc = await PDFDocument.create();
      const font = await doc.embedFont(StandardFonts.Helvetica);
      const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
      const page = doc.addPage([595, 842]); // A4
      const { width, height } = page.getSize();
      const img = await doc.embedPng(qrBytes);

      let y = height - 80;

      if (title) {
        const titleSize = 20;
        const tw = fontBold.widthOfTextAtSize(title.slice(0, 50), titleSize);
        page.drawText(title.slice(0, 50), { x: (width - tw) / 2, y, size: titleSize, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
        y -= 30;
      }

      if (description) {
        const descSize = 11;
        // Word wrap at ~60 chars per line
        const words = description.slice(0, 200).split(' ');
        let line = '';
        const lines: string[] = [];
        words.forEach(word => {
          if ((line + ' ' + word).length > 60) { lines.push(line); line = word; }
          else line = line ? `${line} ${word}` : word;
        });
        if (line) lines.push(line);
        lines.forEach(l => {
          const tw = font.widthOfTextAtSize(l, descSize);
          page.drawText(l, { x: (width - tw) / 2, y, size: descSize, font, color: rgb(0.4, 0.4, 0.4) });
          y -= 16;
        });
        y -= 10;
      }

      // Draw QR code centered
      const qrDrawSize = qrPx * 0.75;
      const qrX = (width - qrDrawSize) / 2;
      const qrY = y - qrDrawSize - 20;
      page.drawImage(img, { x: qrX, y: qrY, width: qrDrawSize, height: qrDrawSize });

      // Content URL below QR
      const urlLabel = content.slice(0, 60) + (content.length > 60 ? '...' : '');
      const urlSize = 8;
      const uw = font.widthOfTextAtSize(urlLabel, urlSize);
      page.drawText(urlLabel, { x: (width - uw) / 2, y: qrY - 20, size: urlSize, font, color: rgb(0.5, 0.3, 0.8) });

      // Footer
      page.drawText('Generated by iCreatePDF.com', {
        x: (width - font.widthOfTextAtSize('Generated by iCreatePDF.com', 8)) / 2,
        y: 30, size: 8, font, color: rgb(0.7, 0.7, 0.7),
      });

      const bytes = await doc.save();
      setDownloadUrl(URL.createObjectURL(new Blob([bytes as any], { type: 'application/pdf' })));
    } catch (err: any) {
      setError(err?.message || 'QR generation failed.');
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="w-full max-w-6xl mx-auto px-6 lg:px-12 py-16">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        <div className="lg:col-span-8 space-y-6">
          <div className="p-6 bg-zinc-950 border border-white/10 rounded-2xl space-y-5">
            <div className="space-y-1.5">
              <label className="text-[10px] font-mono text-white/40 uppercase">QR Code Content (URL or Text) *</label>
              <textarea
                value={content}
                onChange={e => setContent(e.target.value)}
                placeholder="https://example.com or any text..."
                rows={3}
                className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder:text-white/20 focus:outline-none focus:border-purple-500 resize-none"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-[10px] font-mono text-white/40 uppercase">Title (optional)</label>
              <input type="text" value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Scan to visit our website" className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-white/20 focus:outline-none focus:border-purple-500" />
            </div>
            <div className="space-y-1.5">
              <label className="text-[10px] font-mono text-white/40 uppercase">Description (optional)</label>
              <input type="text" value={description} onChange={e => setDescription(e.target.value)} placeholder="A short description below the title" className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-white/20 focus:outline-none focus:border-purple-500" />
            </div>
            <div className="space-y-2">
              <label className="text-[10px] font-mono text-white/40 uppercase">QR Code Size</label>
              <div className="flex gap-2">
                {(['small', 'medium', 'large'] as const).map(s => (
                  <button key={s} onClick={() => setQrSize(s)} className={`px-4 py-2 rounded-xl text-xs capitalize transition-all ${qrSize === s ? 'bg-purple-600 text-white' : 'bg-white/5 text-white/50 hover:bg-white/10'}`}>{s}</button>
                ))}
              </div>
            </div>
          </div>

          {content && (
            <div className="p-6 bg-zinc-950 border border-white/10 rounded-2xl flex flex-col items-center gap-4">
              <p className="text-xs font-mono text-white/40 uppercase">Live QR Preview</p>
              <canvas ref={canvasRef} className="rounded-xl" />
            </div>
          )}
          {error && <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-200 text-sm">{error}</div>}
        </div>

        <div className="lg:col-span-4 bg-zinc-950 border border-white/10 rounded-2xl p-6 space-y-6">
          <div className="flex items-center gap-2 border-b border-white/5 pb-4">
            <QrCode className="w-4 h-4 text-purple-400" />
            <h3 className="font-mono text-sm uppercase tracking-wider text-white">QR to PDF</h3>
          </div>
          <p className="text-xs text-white/50 leading-relaxed">Generate a clean A4 PDF page with a QR code for any URL or text. Add a title and description. Perfect for print materials, posters, menus, and business cards.</p>
          <div className="pt-4 border-t border-white/5">
            {isProcessing ? (
              <Button disabled className="w-full bg-purple-600/50 text-white font-medium py-6 rounded-xl flex items-center justify-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin" />Generating...
              </Button>
            ) : downloadUrl ? (
              <div className="space-y-2">
                <Button onClick={() => { const a = document.createElement('a'); a.href = downloadUrl; a.download = 'qr-code.pdf'; a.click(); }} className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-medium py-6 rounded-xl flex items-center justify-center gap-2">
                  <Download className="w-5 h-5" />Download QR PDF
                </Button>
                <Button variant="ghost" onClick={() => { setDownloadUrl(null); }} className="w-full text-white/50 hover:text-white text-xs h-8">Generate another</Button>
              </div>
            ) : (
              <Button disabled={!content.trim()} onClick={process} className={`w-full font-medium py-6 rounded-xl flex items-center justify-center gap-2 ${content.trim() ? 'bg-purple-600 hover:bg-purple-700 text-white' : 'bg-white/5 text-white/30 cursor-not-allowed'}`}>
                <QrCode className="w-4 h-4" />Generate PDF
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
