import { MetadataRoute } from 'next';

const TODAY = new Date().toISOString().split('T')[0];
const STATIC_DATE = '2026-07-01';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.icreatepdf.online';
  const toolRoutes = [
    '/jpg-to-pdf',
    '/png-to-pdf',
    '/heic-to-pdf',
    '/merge-pdf',
    '/split-pdf',
    '/compress-pdf',
    '/organize-pdf',
    '/rotate-pdf',
    '/watermark-pdf',
    '/add-page-numbers',
    '/pdf-to-jpg',
    '/pdf-to-png',
    '/scan-to-pdf',
    '/word-to-pdf',
    '/protect-pdf',
    '/sign-pdf',
    '/pdf-to-text',
    '/edit-pdf',
    '/verify-signature',
    '/html-to-pdf',
    '/markdown-to-pdf',
    '/flatten-pdf',
    '/grayscale-pdf',
    '/compare-pdf',
    '/unlock-pdf',
    '/redact-pdf',
    '/crop-pdf',
    '/extract-pages',
    '/repair-pdf',
    '/pdf-metadata',
    '/header-footer',
    '/resize-pdf',
    '/bates-numbering',
    '/invert-pdf',
    '/qr-to-pdf',
    '/barcode-to-pdf',
    '/delete-pdf-pages',
    '/txt-to-pdf',
    '/ris-to-pdf',
    '/read-aloud-pdf',
    '/certify-pdf',
    '/pdf-to-excel',
    '/excel-to-pdf',
    '/pdf-accessibility-checker',
    '/prevent-copy',
    '/pdf-ocr',
    '/bulk-certificates',
    '/fillable-pdf-builder',
    '/base64-to-pdf',
    '/n-up-pdf',
    '/booklet-pdf',
    '/adjust-pdf-margins',
    '/equalize-pdf-page-sizes',
    '/pdf-to-word',
    '/extract-pdf-images',
    '/export-pdf-form-data',
    '/pdf-to-audio',
    '/stamp-pdf',
    '/pdf-reading-themes',
    '/pdf-security-auditor',
    '/pdf-toc-builder',
    '/epub-to-pdf',
    '/svg-to-pdf',
    '/csv-to-pdf',
    '/auto-redact-pdf',
    '/pdf-attachment-manager',
    '/pdf-visual-diff',
    '/pdf-3d-flipbook',
    '/pdf-presentation-mode',
    '/auto-crop-pdf',
  ];

  const blogRoutes = [
    '/blogs',
    '/blogs/how-to-compress-pdf-to-200kb-online',
    '/blogs/how-to-edit-pdf-on-mac-free',
    '/blogs/how-to-save-pdf-as-jpg',
    '/blogs/how-to-split-pdf-files',
    '/blogs/how-to-auto-redact-pdf-sensitive-data',
    '/blogs/how-to-manage-and-embed-pdf-attachments',
    '/blogs/how-to-compare-pdf-visual-diff',
    '/blogs/how-to-create-interactive-3d-pdf-flipbook',
    '/blogs/how-to-present-pdf-slideshow-laser-pointer',
    '/blogs/how-to-auto-crop-pdf-margins',
    '/blogs/how-to-create-n-up-pdf',
    '/blogs/how-to-make-pdf-booklet',
    '/blogs/how-to-adjust-pdf-margins',
    '/blogs/how-to-equalize-pdf-page-sizes',
    '/blogs/how-to-convert-pdf-to-word',
    '/blogs/how-to-extract-images-from-pdf',
    '/blogs/how-to-export-pdf-form-data',
    '/blogs/how-to-listen-to-pdf-audio',
    '/blogs/how-to-stamp-pdf-pages',
    '/blogs/how-to-apply-pdf-reading-themes',
    '/blogs/how-to-audit-pdf-security',
    '/blogs/how-to-build-pdf-table-of-contents',
    '/blogs/how-to-convert-epub-to-pdf',
    '/blogs/how-to-convert-svg-to-pdf',
    '/blogs/how-to-convert-csv-to-pdf',
    '/blogs/how-to-convert-base64-to-pdf',
    '/blogs/how-to-verify-pdf-signature',
    '/blogs/how-to-certify-pdf-with-fingerprint',
    '/blogs/how-to-convert-markdown-to-pdf',
    '/blogs/how-to-convert-txt-to-pdf',
    '/blogs/how-to-convert-ris-to-pdf-bibliography',
    '/blogs/how-to-listen-to-pdf-text-to-speech',
    '/blogs/pdf-accessibility-checker-guide',
    '/blogs/how-to-add-header-footer-to-pdf',
    '/blogs/how-to-compare-two-pdf-files',
    '/blogs/how-to-generate-qr-code-pdf',
    '/blogs/how-to-generate-barcode-pdf',
    '/blogs/how-to-delete-pages-from-pdf',
    '/blogs/how-to-scan-documents-to-pdf',
    '/blogs/how-to-organize-pdf-pages',
    '/blogs/how-to-convert-html-to-pdf',
    '/blogs/how-to-convert-pdf-to-excel',
    '/blogs/how-to-convert-excel-to-pdf',
    '/blogs/how-to-crop-pdf-pages',
    '/blogs/how-to-resize-pdf-pages',
    '/blogs/how-to-repair-corrupted-pdf',
    '/blogs/how-to-convert-pdf-to-jpg',
    '/blogs/how-to-rotate-pdf-pages',
    '/blogs/how-to-extract-text-from-pdf',
    '/blogs/how-to-edit-pdf-online-free',
    '/blogs/proof-zero-server-uploads-how-to-verify-offline-pdf-converter',
    '/blogs/how-to-compress-pdf-without-losing-quality',
    '/blogs/how-to-merge-pdf-files-free',
    '/blogs/how-to-sign-pdf-online-free',
    '/blogs/jpg-to-pdf-complete-guide',
    '/blogs/how-to-convert-iphone-photos-to-pdf',
    '/blogs/best-free-image-to-pdf-tools-2026',
    '/blogs/how-to-redact-pdf-online-free',
    '/blogs/how-to-extract-pages-from-pdf',
    '/blogs/how-to-edit-pdf-metadata',
    '/blogs/bates-numbering-pdf-guide',
    '/blogs/how-to-invert-pdf-colors-dark-mode',
    '/blogs/how-to-prevent-copying-text-from-pdf',
    '/blogs/how-to-convert-scanned-pdf-to-text-ocr',
    '/blogs/how-to-generate-certificates-in-bulk',
    '/blogs/how-to-password-protect-and-unlock-pdf',
    '/blogs/how-to-convert-word-docx-to-pdf-free',
    '/blogs/how-to-split-pdf-pages-free',
    '/blogs/how-to-grayscale-and-flatten-pdf',
    '/blogs/how-to-add-watermark-and-page-numbers-to-pdf',
    '/blogs/how-to-create-fillable-pdf-forms-free',
  ];

  const staticRoutes = [
    '/contact',
    '/privacy',
    '/terms',
    '/about',
    '/authors/barath-r',
    '/editorial-policy',
    '/embed',
    '/adsense-policy',
  ];

  const comparisonRoutes = [
    '/compare',
    '/compare/adobe-acrobat-alternative',
    '/compare/sejda-alternative',
    '/compare/ilovepdf-alternative',
    '/compare/smallpdf-alternative',
    '/compare/pdf24-alternative',
    '/no-upload-pdf-tools',
  ];

  const langRoutes = [
    '/es',
    '/pt',
    '/id',
    '/de',
    '/ja',
    '/fr',
    '/hi',
    '/ta',
  ];

  return [
    // Homepage — highest priority
    {
      url: `${baseUrl}/`,
      lastModified: TODAY,
      changeFrequency: 'daily',
      priority: 1.0,
      alternates: {
        languages: {
          en: `${baseUrl}/`,
          es: `${baseUrl}/es`,
          pt: `${baseUrl}/pt`,
          id: `${baseUrl}/id`,
          de: `${baseUrl}/de`,
          ja: `${baseUrl}/ja`,
          fr: `${baseUrl}/fr`,
          hi: `${baseUrl}/hi`,
          ta: `${baseUrl}/ta`,
          'x-default': `${baseUrl}/`,
        },
      },
    },
    // Tool pages — core content
    ...toolRoutes.map((route) => {
      const cleanRoute = route.startsWith('/tools/')
        ? route.replace('/tools/', '/')
        : route;
      return {
        url: `${baseUrl}${cleanRoute}`,
        lastModified: TODAY,
        changeFrequency: 'weekly' as const,
        priority: 0.9,
      };
    }),
    // Blog pages
    ...blogRoutes.map((route) => ({
      url: `${baseUrl}${route}`,
      lastModified: TODAY,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    })),
    // Static pages (Contact, Privacy, Terms, About)
    ...staticRoutes.map((route) => ({
      url: `${baseUrl}${route}`,
      lastModified: STATIC_DATE,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    })),
    // Comparison / alternative pages — commercial intent
    ...comparisonRoutes.map((route) => {
      const cleanRoute = route.startsWith('/tools/')
        ? route.replace('/tools/', '/')
        : route;
      return {
        url: `${baseUrl}${cleanRoute}`,
        lastModified: TODAY,
        changeFrequency: 'monthly' as const,
        priority: 0.7,
      };
    }),
    // Localised landing pages
    ...langRoutes.map((route) => ({
      url: `${baseUrl}${route}`,
      lastModified: TODAY,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    })),
  ];
}
